title: 하루 한 편
email: guseod24@gmail.com
description: |
  하루 한편, 생각과 일상을 글로 남깁니다.
  솔직하고 담백한 글을 씁니다.
baseurl: ''
url: 'http://seolkiwhite.github.io'
timezone: Asia/Seoul 

repository: SeolkiWhite/seolkiwhite.github.io

permalink: /:year/:month/:day/:title/

excerpt_separator: <!--more-->

markdown: kramdown

krandown:
  input: GFM
  highlighter: rouge

plugins:
  - jekyll-paginate

paginate: 5
paginate_path: '/page/:num/'

collections:
  authors:
    output: true
    permalink: /authors/:path/
  tags:
    output: true
    permalink: /tags/:path/

defaults:
  - scope:
      path: ''
      type: authors
    values:
      layout: author
  - scope:
      path: ''
      type: tags
    values:
      layout: tag

exclude: [
  README.md,
  Gemfile,
  Gemfile.lock,
  node_modules,
  vendor/bundle/,
  vendor/cache/,
  vendor/gems/,
  vendor/ruby/,
  any_additional_item # any user-specific listing goes at the end
]

keep_files: [assets, files]
github: [metadata]
# iolo's custom
author: seolki
image: '/assets/images/default_blog_cover.jpg'
asset_url: /assets
#asset_url: //meta-kage.kakaocdn.net/dn/osa/blog/assets
#asset_url: //t1.daumcdn.net/osa/blog/assets
google_analytics:
  ua: 'UA-72007721-1'
# facebook:
#   app_id: '1204347326263800'
#   username: nkakao
# twitter:
#   username: kakaodev
# google_plus:
#   username: kakaodev
# github_url:
#   username: kakao
